export const LOGIN_PAGE_ON_LOGIN_TAP = 'LOGIN_PAGE_ON_LOGIN_TAP';
export const LOGIN_PAGE_ON_LOGIN_REQUEST = 'LOGIN_PAGE_ON_LOGIN_REQUEST';
export const LOGIN_PAGE_ON_RECEIVE_LOGIN_DATA = 'LOGIN_PAGE_ON_RECEIVE_LOGIN_DATA';
export const LOGIN_PAGE_ON_RECEIVE_LOGIN_ERRORS = 'LOGIN_PAGE_ON_RECEIVE_LOGIN_ERRORS';
export const LOGIN_PAGE_CLEAR_ERRORS = 'LOGIN_PAGE_CLEAR_ERRORS';
export const LOGIN_PAGE_SET_BUTTON_ENABLED = 'LOGIN_PAGE_SET_BUTTON_ENABLED';
export const LOGIN_PAGE_SET_BUTTON_DISABLED = 'LOGIN_PAGE_SET_BUTTON_DISABLED';
