export const DEAL_PAGE_ON_TOGGLE_TAPPED = 'DEAL_PAGE_ON_TOGLLE_TAPPED';
export const DEAL_PAGE_ON_SHOW_PROFILE_DIALOG = 'DEAL_PAGE_ON_SHOW_PROFILE_DIALOG';
export const DEAL_PAGE_ON_HIDE_PROFILE_DIALOG = 'DEAL_PAGE_ON_HIDE_PROFILE_DIALOG';
export const DEAL_PAGE_FETCH_USER_PROFILES_DATA_REQUEST = 'DEAL_PAGE_FETCH_USER_PROFILES_DATA_REQUEST';
export const DEAL_PAGE_RECEIVE_USER_PROFILES_DATA = 'DEAL_PAGE_RECEIVE_USER_PROFILES_DATA'; 
export const DEAL_PAGE_ON_SAVE_NEW_PROFILE_REQUEST = 'DEAL_PAGE_ON_SAVE_NEW_PROFILE_REQUEST';
export const DEAL_PAGE_RECEIVE_SAVED_NEW_PROFILE_DATA = 'DEAL_PAGE_RECEIVE_SAVED_NEW_PROFILE_DATA';
export const DEAL_PAGE_RECEIVE_SAVED_NEW_PROFILE_ERRORS = 'DEAL_PAGE_RECEIVE_SAVED_NEW_PROFILE_ERRORS';

export const DEAL_PAGE_ON_PROFILE_SELECTED = 'DEAL_PAGE_ON_PROFILE_SELECTED';
export const DEAL_PAGE_ON_CANCEL_PROFILE_SELECTED = 'DEAL_PAGE_ON_CANCEL_PROFILE_SELECTED';
export const DEAL_PAGE_ON_PROFILE_TEMP_SELECTED = 'DEAL_PAGE_ON_PROFILE_TEMP_SELECTED';

export const DEAL_PAGE_ON_SAVE_NEW_PROFILE_FROM_DIALOG_REQUEST = 'DEAL_PAGE_ON_SAVE_NEW_PROFILE_FROM_DIALOG_REQUEST';
export const DEAL_PAGE_ON_SWITCH_PROFILE = 'DEAL_PAGE_ON_SWITCH_PROFILE';
export const DEAL_PAGE_ON_SWITCH_OFFER = 'DEAL_PAGE_ON_SWITCH_OFFER';

export const TOGGLE_STATUS_BUY = 'BELI';
export const TOGGLE_STATUS_SELL = 'JUAL';
export const TOGGLE_STATUS_EDIT = 'EDIT';

export const DEAL_PAGE_ON_SWITCH_TO_FREEZE_TOGGLE = 'DEAL_PAGE_ON_SWITCH_TO_FREEZE_TOGGLE';
export const DEAL_PAGE_SET_TOGGLE_STATUS = 'DEAL_PAGE_SET_TOGGLE_STATUS';

export const DEAL_PAGE_ON_USER_CHOICE_IMAGE = 'DEAL_PAGE_ON_USER_CHOICE_IMAGE';
export const DEAL_PAGE_ON_USER_REMOVE_IMAGE = 'DEAL_PAGE_ON_USER_REMOVE_IMAGE';