export const DEAL_PAGE_ON_TOGGLE_TAPPED = 'DEAL_PAGE_ON_TOGLLE_TAPPED';
export const DEAL_PAGE_ON_SHOW_PROFILE_DIALOG = 'DEAL_PAGE_ON_SHOW_PROFILE_DIALOG';
export const DEAL_PAGE_ON_HIDE_PROFILE_DIALOG = 'DEAL_PAGE_ON_HIDE_PROFILE_DIALOG';
export const TOGGLE_STATUS_BUY = 'BELI';
export const TOGGLE_STATUS_SELL = 'JUAL';