export const MAKE_DEAL_PAGE_FETCH_USER_CONTACTS_DATA_REQUEST = 'MAKE_DEAL_PAGE_FETCH_USER_CONTACTS_DATA_REQUEST';
export const MAKE_DEAL_PAGE_RECEIVE_USER_CONTACTS_DATA = 'MAKE_DEAL_PAGE_RECEIVE_USER_CONTACTS_DATA';

export const MAKE_DEAL_PAGE_SHOW_SELECT_CONTACT_DIALOG = 'MAKE_DEAL_PAGE_SHOW_SELECT_CONTACT_DIALOG';
export const MAKE_DEAL_PAGE_HIDE_SELECT_CONTACT_DIALOG = 'MAKE_DEAL_PAGE_HIDE_SELECT_CONTACT_DIALOG';
export const MAKE_DEAL_PAGE_ON_CONTACT_SELECTED = 'MAKE_DEAL_PAGE_ON_CONTACT_SELECTED';
export const MAKE_DEAL_PAGE_ON_CONTACT_FINAL_SELECTED = 'MAKE_DEAL_PAGE_ON_CONTACT_FINAL_SELECTED';

export const MAKE_DEAL_PAGE_ON_ADD_ITEM = 'MAKE_DEAL_PAGE_ON_ADD_ITEM';
export const MAKE_DEAL_PAGE_ON_REMOVE_ITEM = 'MAKE_DEAL_PAGE_ON_REMOVE_ITEM';

export const MAKE_DEAL_PAGE_ON_PLUS_TAP = 'MAKE_DEAL_PAGE_ON_PLUS_TAP';
export const MAKE_DEAL_PAGE_ON_MINUS_TAP = 'MAKE_DEAL_PAGE_ON_MINUS_TAP';

export const MAKE_DEAL_PAGE_ON_PLUS_TAP_ITEM = 'MAKE_DEAL_PAGE_ON_PLUS_TAP_ITEM';
export const MAKE_DEAL_PAGE_ON_MINUS_TAP_ITEM = 'MAKE_DEAL_PAGE_ON_MINUS_TAP_ITEM';

export const MAKE_DEAL_PAGE_ON_ITEM_PRICE_CHANGE = 'MAKE_DEAL_PAGE_ON_ITEM_PRICE_CHANGE';

export const MAKE_DEAL_SAVE_PRODUCT_REQUEST = 'MAKE_DEAL_SAVE_PRODUCT_REQUEST';
export const MAKE_DEAL_RECEIVE_PRODUCT_DATA = 'MAKE_DEAL_RECEIVE_PRODUCT_DATA';
export const MAKE_DEAL_RECEIVE_PRODUCT_ERRORS = 'MAKE_DEAL_RECEIVE_PRODUCT_ERRORS';

export const MAKE_DEAL_RESET_ERRORS_FIELD = 'MAKE_DEAL_RESET_ERRORS_FIELD';
export const MAKE_DEAL_RESET_ERRORS_ITEM_FIELD = 'MAKE_DEAL_RESET_ERRORS_ITEM_FIELD';

export const MAKE_DEAL_ON_USER_CHOICE_IMAGE = 'MAKE_DEAL_ON_USER_CHOICE_IMAGE';
export const MAKE_DEAL_ON_USER_REMOVE_IMAGE = 'MAKE_DEAL_ON_USER_REMOVE_IMAGE';

export const MAKE_DEAL_ON_USER_CHOICE_CREATION_PRODUCT_MODE = 'MAKE_DEAL_ON_USER_CHOICE_CREATION_PRODUCT_MODE';

export const MAKE_DEAL_ON_SELECT_CONTACT_SEARCH_KEY_CHANGE = 'MAKE_DEAL_ON_SELECT_CONTACT_SEARCH_KEY_CHANGE';
export const MAKE_DEAL_RESET_CONTACTS_DATA = 'MAKE_DEAL_RESET_CONTACTS_DATA';

export const MAKE_DEAL_ON_CONTACT_CLICK = 'MAKE_DEAL_ON_CONTACT_CLICK';
