export const SHOPPING_LIST_PAGE_ON_CUSTOM_TAB_TAP = 'SHOPPING_LIST_PAGE_ON_CUSTOM_TAB_TAP';


export const SHOPPING_LIST_PAGE_CUSTOM_TAB_BUYER = 'BUYER';
export const SHOPPING_LIST_PAGE_CUSTOM_TAB_SELLER = 'SELLER';