export const GLOBAL_SET_FLASH_MESSAGE = 'GLOBAL_SET_FLASH_MESSAGE';
export const GLOBAL_CLEAR_FLASH_MESSAGE = 'GLOBAL_CLEAR_FLASH_MESSAGE';
export const GLOBAL_UNSET_FLASH_MESSAGE = 'GLOBAL_UNSET_FLASH_MESSAGE';