export const PRODUCT_LIST_PAGE_SHOW_PROFILE_DIALOG = 'PRODUCT_LIST_PAGE_SHOW_PROFILE_DIALOG';
export const PRODUCT_LIST_PAGE_HIDE_PROFILE_DIALOG = 'PRODUCT_LIST_PAGE_HIDE_PROFILE_DIALOG';
export const PRODUCT_LIST_PAGE_RECEIVE_PROFILE_DATA = 'PRODUCT_LIST_PAGE_RECEIVE_PROFILE_DATA';

export const PRODUCT_LIST_PAGE_ON_USER_SELECTED_PROFILE = 'PRODUCT_LIST_PAGE_ON_USER_SELECTED_PROFILE';
export const PRODUCT_LIST_PAGE_ON_USER_CANCELED_SELECT_PROFILE = 'PRODUCT_LIST_PAGE_ON_USER_CANCELED_SELECT_PROFILE';
export const PRODUCT_LIST_PAGE_ON_USER_SELECTED_PROFILE_FINAL = 'PRODUCT_LIST_PAGE_ON_USER_SELECTED_PROFILE_FINAL';

export const TOGGLE_STATUS_PRODUCT_LIST = 'Products';
export const PRODUCT_LIST_PAGE_CREATE_MODE = 'PRODUCT_LIST_PAGE_CREATE_MODE';
export const PRODUCT_LIST_PAGE_LIST_MODE = 'PRODUCT_LIST_PAGE_LIST_MODE';

export const PRODUCT_LIST_PAGE_CHANGE_MODE = 'PRODUCT_LIST_PAGE_CHANGE_MODE';

export const PRODUCT_LIST_PAGE_ON_ADD_ITEM = 'PRODUCT_LIST_PAGE_ON_ADD_ITEM';
export const PRODUCT_LIST_PAGE_ON_REMOVE_ITEM = 'PRODUCT_LIST_PAGE_ON_REMOVE_ITEM';
export const PRODUCT_LIST_PAGE_ON_PLUS_TAP_ITEM = 'PRODUCT_LIST_PAGE_ON_PLUS_TAP_ITEM';
export const PRODUCT_LIST_PAGE_ON_MINUS_TAP_ITEM = 'PRODUCT_LIST_PAGE_ON_MINUS_TAP_ITEM';